# Generated by Django 6.0.5 on 2026-05-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('duracao_minutos', models.PositiveIntegerField()),
                ('formato', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('4D', '4D'), ('IMAX', 'IMAX')], default='2D', max_length=10)),
            ],
        ),
    ]
