# Generated by Django 6.0.5 on 2026-06-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo_desconto', models.CharField(choices=[('percentual', 'Percentual'), ('fixo', 'Valor fixo')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validade', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('limite_usos', models.PositiveIntegerField(blank=True, null=True)),
                ('quantidade_usos', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
