# Generated by Django 6.0.5 on 2026-06-09 20:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('canal', models.CharField(choices=[('web', 'Web'), ('app', 'Aplicativo'), ('bilheteria', 'Bilheteria')], default='web', max_length=20)),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_final', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='sessoes.sessao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inteira', 'Inteira'), ('meia', 'Meia-entrada'), ('meia_idoso', 'Meia-entrada idoso'), ('meia_santander', 'Meia Santander')], max_length=30)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('assento_sessao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ingresso', to='sessoes.assentosessao')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to='vendas.venda')),
            ],
        ),
    ]
