# Generated by Django 6.0.6 on 2026-06-25 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessoes', '0001_initial'),
        ('vendas', '0002_venda_cupom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresso',
            name='assento_sessao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingressos', to='sessoes.assentosessao'),
        ),
    ]
