# Generated by Django 6.0.5 on 2026-05-26 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(max_length=5)),
                ('numero', models.PositiveIntegerField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assentos', to='cinemas.sala')),
            ],
            options={
                'ordering': ['fila', 'numero'],
                'unique_together': {('sala', 'fila', 'numero')},
            },
        ),
    ]
