# Generated by Django 6.0.5 on 2026-05-26 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assentos', '0001_initial'),
        ('catalogo', '0001_initial'),
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativa', models.BooleanField(default=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='catalogo.filme')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='cinemas.sala')),
            ],
        ),
        migrations.CreateModel(
            name='AssentoSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('vendido', 'Vendido')], default='disponivel', max_length=20)),
                ('reservado_ate', models.DateTimeField(blank=True, null=True)),
                ('assento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='assentos.assento')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assentos_sessao', to='sessoes.sessao')),
            ],
            options={
                'unique_together': {('sessao', 'assento')},
            },
        ),
    ]
